server {
    listen 80;
    absolute_redirect off;
    resolver 127.0.0.11 valid=10s;

    location = /student {
        return 301 /student/;
    }

    location /student/ {
        set $student_app http://student-php:80;
        rewrite ^/student/(.*)$ /$1 break;
        proxy_pass $student_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 20m;
    }

    location /assets/ {
        alias /usr/share/nginx/assets/;
        add_header X-Content-Type-Options nosniff;
        expires 1h;
    }

    location / {
        set $adviser_app http://adviser-node:8080;
        proxy_pass $adviser_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
